spring:
  cloud:
    gateway:
      routes:
      - id: test_route
        uri: https://www.baidu.com
        predicates:
          - Query=url,baidu

      - id: qq_route
        uri: https://www.qq.com
        predicates:
          - Query=url,qq

    ##精确的路由放前面
      - id: product_route
        uri: lb://shopmail-product
        predicates:
          - Path=/api/shopmailproduct/**
        filters:
          - RewritePath=/api/(?<segment>.*),/$\{segment}
      - id: third_party_route
        uri: lb://shopmail-third-party
        predicates:
          - Path=/api/shopmailthirdparty/**
        filters:
          - RewritePath=/api/shopmailthirdparty/(?<segment>.*),/$\{segment}

      - id: admin_route
        uri: lb://renren-fast
        predicates:
          - Path=/api/**
        filters:
          - RewritePath=/api/(?<segment>.*), /renren-fast/$\{segment}
 ##前端项目，/api
 ##http://localhost:88/api/captcha.jpg -> http://localhost:8080/renren-fast/captcha.jpg


